### ISSUE TITLE
Pass all SQL test in spansql tests

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/memefish#115]
Result
https://github.com/apstndb/memefish-testsuite/blob/440786a9cead1c7d25a833c9c9de5868976e67e4/output/result.txt

List(TODO: Create individual issues)

* [x] `SYNONYM`s in `CREATE TABLE` #125 
* [x] `DROP VIEW` statement #126
* [x] `GRANT/REVOKE SELECT ON CHANGE STREAM` #127
* [x] `ALTER TABLE ALTER COLUMN DROP DEFAULT` #92 
* [x] `ALTER TABLE ADD/DROP SYNONYM` #128
* [x] `ALTER TABLE RENAME TO, ADD SYNONYM` #129
* [x] `ALTER STATISTICS` #162
* [x] `RENAME TABLE` statement #130 
* [x] `ALTER DATABASE` statement #131 
* [x] `UPDATE SET DEFAULT` #132 
* [x] `SAFE_CAST(expr AS type)` related #94 
* [x] `AGG_FUNC(IGNORE NULLS HAVING MAX)` #88 
* [x] JSON literals #117

**Comment by apstndb** [comment]
Now we have passed all test in spansql's `TestSQL()`!
https://github.com/apstndb/memefish-testsuite/commit/cfb6d624fa59f8eadd470d13c8455f49efd333ac

It is a important milestone that memefish becomes the most feature complete parser for Cloud Spanner's GoogleSQL!
