### ISSUE TITLE
Support PROTO related syntax

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/memefish#89]
https://cloud.google.com/spanner/docs/reference/standard-sql/protocol-buffers

* [x] [`[CREATE | DROP | ALTER] PROTO BUNDLE` statements](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#proto_bundle_statements) https://github.com/cloudspannerecosystem/memefish/pull/176
* [x] [`CAST AS PROTO`](https://cloud.google.com/spanner/docs/reference/standard-sql/conversion_functions#cast_as_proto) #121
* [x] [`NEW` operator] https://github.com/cloudspannerecosystem/memefish/pull/183(https://cloud.google.com/spanner/docs/reference/standard-sql/operators#new_operator) #119
* [x] [`SELECT AS typename`](https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#select_as_typename) #122
* [x] `PROTO`s  as type name #121

### FYI
These functionalities are under developed also in spansql.
* https://github.com/googleapis/google-cloud-go/issues/10944
* https://github.com/googleapis/google-cloud-go/pull/10945

**Comment by apstndb** [comment]
Protocol Buffers support seems to be completed!
